//
// ApiKeysAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class ApiKeysAPI {

    /**
     получить данные об api key
     
     - parameter apiKey: (path) api key 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ApiKeyResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1ApiKeysApiKeyGet(apiKey: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ApiKeyResponse {
        return try await apiV1ApiKeysApiKeyGetWithRequestBuilder(apiKey: apiKey, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     получить данные об api key
     - GET /api/v1/api_keys/{apiKey}
     - parameter apiKey: (path) api key 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ApiKeyResponse> 
     */
    open class func apiV1ApiKeysApiKeyGetWithRequestBuilder(apiKey: String, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<ApiKeyResponse> {
        var localVariablePath = "/api/v1/api_keys/{apiKey}"
        let apiKeyPreEscape = "\(APIHelper.mapValueToPathItem(apiKey))"
        let apiKeyPostEscape = apiKeyPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{apiKey}", with: apiKeyPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApiKeyResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
