//
// MediaPostsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class MediaPostsAPI {

    /**
     получить медиа новости с сайта кинопоиск
     
     - parameter page: (query) номер страницы (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: MediaPostsResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1MediaPostsGet(page: Int? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> MediaPostsResponse {
        return try await apiV1MediaPostsGetWithRequestBuilder(page: page, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     получить медиа новости с сайта кинопоиск
     - GET /api/v1/media_posts
     - Одна страница может содержать до 20 элементов в items.
     - parameter page: (query) номер страницы (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<MediaPostsResponse> 
     */
    open class func apiV1MediaPostsGetWithRequestBuilder(page: Int? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<MediaPostsResponse> {
        let localVariablePath = "/api/v1/media_posts"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MediaPostsResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
