//
// PersonsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class PersonsAPI {

    /**
     поиск актеров, режиссеров и т.д. по имени
     
     - parameter name: (query) имя человека 
     - parameter page: (query) номер страницы (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PersonByNameResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func apiV1PersonsGet(name: String, page: Int? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> PersonByNameResponse {
        return try await apiV1PersonsGetWithRequestBuilder(name: name, page: page, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     поиск актеров, режиссеров и т.д. по имени
     - GET /api/v1/persons
     - Одна страница может содержать до 50 элементов в items.
     - parameter name: (query) имя человека 
     - parameter page: (query) номер страницы (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PersonByNameResponse> 
     */
    open class func apiV1PersonsGetWithRequestBuilder(name: String, page: Int? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<PersonByNameResponse> {
        let localVariablePath = "/api/v1/persons"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "name": (wrappedValue: name.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "page": (wrappedValue: page?.encodeToJSON(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PersonByNameResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
